---
# Source: iter8-analytics/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: iter8
---
# Source: iter8-analytics/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: iter8-analytics
  namespace: iter8
  labels:
    app: iter8-analytics
data: 
  config.yaml: |
    port: 8080
    metricsBackend:
      url: http://prometheus.istio-system:9090
      auth:
        ca_file: 
        insecure_skip_verify: false
        password: 
        token: 
        type: none
        username: 

---
# Source: iter8-analytics/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: iter8-analytics
  namespace: iter8
  labels:
    app: iter8-analytics
spec:
  selector:
    app: iter8-analytics
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http

---
# Source: iter8-analytics/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iter8-analytics
  namespace: iter8
  labels:
    name: iter8-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iter8-analytics
  template:
    metadata:
      labels:
        app: iter8-analytics
    spec:
      containers:
        - name: iter8-analytics
          image: "merttoslali/iter8-analytics:testexp3"
          imagePullPolicy: IfNotPresent
          env:
            - name: METRICS_BACKEND_CONFIGFILE
              value: "config.yaml"
          resources:
            {}
            
          volumeMounts:
            - name: config-volume
              mountPath: /config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap: 
            name: iter8-analytics

