"""
Environment variables that control the iter8 analytics server
"""

ITER8_ANALYTICS_SERVER_PORT_ENV = 'ITER8_ANALYTICS_SERVER_PORT'
ITER8_ANALYTICS_DEBUG_ENV = 'ITER8_ANALYTICS_DEBUG'

ITER8_ANALYTICS_METRICS_BACKEND_URL_ENV = 'ITER8_ANALYTICS_METRICS_BACKEND_URL'
ITER8_DATA_CAPTURE_MODE_ENV = 'ITER8_DATA_CAPTURE_MODE'
